### ISSUE TITLE
draw.io after monthly log

### ISSUE THREAD

**Issue by ghost** [Max-Edelson/cse110-sp21-group16#1]
By definition of monthly log, it has nothing to do with the daily log. It might have something to do with the exact dates. I think Monthly log will be a list. It might starts with a date or not. When we click the calender in the monthly log, I believe the things that show up will be the things you input for monthly log, not daily log.

**Comment by Max-Edelson** [comment]
Well so my thinking was that the user might be in the daily log, but when they are done looking at it or altering it, they can go to the monthly log which gives them a calendar-like view of the month with tasks/events/notes so that they can have an overview. What do you think?

**Comment by ghost** [comment]
That is more like a calendar in daily log, right? I think when you enter the daily log, you will have a calendar for this month. Today's date will be highlighted. Monthly log is more general than daily log. I think it is better to differentiate them. Let's see what other team members think.

**Comment by Max-Edelson** [comment]
Yeah sounds good, can you add that discussion to the agenda for Monday please? I've already made the meeting file. I was thinking that the daily log would be more like google-calendar style with a vertical clock for events and another page with notes/tasks. and then the monthly log was a calendar but we can discuss Monday.
