### ISSUE TITLE
Event Object Demo Requested

### ISSUE THREAD

**Issue by InfernalDrago** [Max-Edelson/cse110-sp21-group16#11]
Can someone from the collections team send me a code sample of an event object? I'm gonna use it to test out the monthly log calendar and list.

**Comment by Ovijavi** [comment]
Can we actually get your html code so we can try to figure out how to connect the code to the webpage?

**Comment by InfernalDrago** [comment]
Here's a copy of the html, css, and js of the calendar. 
[caleandar-master copy 2.zip](https://github.com/Max-Edelson/cse110-sp21-group16/files/6505148/caleandar-master.copy.2.zip)

**Comment by Max-Edelson** [comment]
Completed.
