### ISSUE TITLE
Bug in Item.js

### ISSUE THREAD

**Issue by Max-Edelson** [Max-Edelson/cse110-sp21-group16#12]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/56405133/118565237-a59b7100-b726-11eb-982c-aa7edef09898.png">

**Comment by Max-Edelson** [comment]
Every item needs a getter and setter for each "property" or internal value.

**Comment by Max-Edelson** [comment]
Also, when you are making a setter, follow the following format: 
```
set title(title) {
    this._title = title;
}
```

**Comment by Ovijavi** [comment]
fixed this while working on the demo
