### ISSUE TITLE
Ambiguity in Monthly_Log.js

### ISSUE THREAD

**Issue by Max-Edelson** [Max-Edelson/cse110-sp21-group16#33]
I am trying to create unit tests for Monthly_Log.js rn and I'm looking at ```this.days = [];``` and I have no idea what ```days``` is holding. Is it simply holding a number of days? Or is it holding a day object? If it is only holding a number, what benefit does that provide? Also, didn't we discuss that the monthly log would hold day objects?

**Comment by carmenli14** [comment]
We actually probably won't use this class because we are refactoring some things to incorporate localStorage.

**Comment by Max-Edelson** [comment]
Okay sounds good.
