### ISSUE TITLE
Create Future Log

### ISSUE THREAD

**Issue by joshua-j-hong** [Max-Edelson/cse110-sp21-group16#35]
The future log should conform stylistically to the figma templates 
https://www.figma.com/file/52Zkw8Cj4xodNHTyGyPLV5/banananotes?node-id=0%3A1 

- [x] General HTML Look
- [x] JS Component version
- [ ] Fix Coding  Style

**Comment by joshua-j-hong** [comment]
Update: Future log is done, all that remains is to add event listeners and integrate local storage so the page functions

**Comment by Max-Edelson** [comment]
Done. Maybe some small style changed. New Issue?
