### ISSUE TITLE
Create Monthly Log Calendar View/List View

### ISSUE THREAD

**Issue by joshua-j-hong** [Max-Edelson/cse110-sp21-group16#37]
The Monthly Log should have two separate viewing options. The first should be a traditional calendar, with the option to click on a date to open the daily log of the day. The second should be a list view where notes are shown chronologically for the month

- [ ] General Visual Look
- [ ] JS Component

Feel free to document work/progress here.

**Comment by Max-Edelson** [comment]
Done.
