### ISSUE TITLE
Event object needs time field

### ISSUE THREAD

**Issue by Max-Edelson** [Max-Edelson/cse110-sp21-group16#51]
As the title says, the Event object needs to allow for a time input because an event occurs usually at a specific time.

**Comment by Max-Edelson** [comment]
Oh unless the time is in the date object. Let me know if it is or isn't.

**Comment by Ovijavi** [comment]
The date object is a string that holds the current day (given by user using the date input element). I think we should keep it as a day for now and add the time feature later

**Comment by Max-Edelson** [comment]
Sounds good.
