### ISSUE TITLE
BUG: Navbar glitching

### ISSUE THREAD

**Issue by Max-Edelson** [Max-Edelson/cse110-sp21-group16#63]
**Describe the bug**

**To Reproduce**
If the page is loaded while the cursor is over the area the nabber takes, then the navbar is rendered unusable as it expands when the cursor moves away and contracts when the user tries to click on it.

**Additional context**
A video on slack shows this issue in action: https://cse110-sp21-group16.slack.com/archives/C01TF2JFNTV/p1622609381010300

**Comment by joshua-j-hong** [comment]
Fixed with commit cc4ba4c2821608dda0f70a6e7fe2eb8ba365bdad
