### ISSUE TITLE
ENHANCEMENT: Custom Log Aethstetic

### ISSUE THREAD

**Issue by Max-Edelson** [Max-Edelson/cse110-sp21-group16#65]
**Enhancement details**

**What will this enhancement affect (pages/code)?**
- The screenshot below shows the custom log as it currently is.

**What will be the affect of this enhancement?**
- This log has to be cleaned up quite a bit
- Where the user is actual supposed to type is not super clear
- The log only really takes in notes but it should take in events and tasks too
- The purple box seems unnecessarily large
- Missing the nav bar

**Other notes**
<img width="1440" alt="Screen Shot 2021-06-01 at 9 54 38 PM" src="https://user-images.githubusercontent.com/56405133/120425943-fc5a9a80-c323-11eb-8f16-2e752382e894.png">

**Comment by ghost** [comment]
I am wondering it will be same as the rapid log if we allow all of the tasks, events, and notes. I personally think custom log will be a place to write notes.

**Comment by ghost** [comment]
When I merge all the logs tgt, my style for custom log has lost. I will keep working on it.

**Comment by Max-Edelson** [comment]
Nevermind, the custom log should not have events or tasks.

**Comment by Max-Edelson** [comment]
Okay, that sounds good.

**Comment by Max-Edelson** [comment]
Fixed.
