### ISSUE TITLE
Add sidebar to Monthly Log List

### ISSUE THREAD

**Issue by InfernalDrago** [Max-Edelson/cse110-sp21-group16#69]
Joshua, I've uploaded the blank version of monthly log list to the general_frontend branch under source/frontend/monthlylog_list. Could you implement the sidebar to that page?

**Comment by joshua-j-hong** [comment]
Addressed in 901f464dcada287b7b5b3903bae2be3e646539a1

**Comment by Max-Edelson** [comment]
Not enough time for list view for monthly log.
