### ISSUE TITLE
ENHANCEMENT: Initial Rapid Log Thoughts

### ISSUE THREAD

**Issue by Max-Edelson** [Max-Edelson/cse110-sp21-group16#72]
Potential Updates/Fixes
- [ ] After inserting a new item, have the insertion menu disappear instead of expect more item insertions.
- [ ] New item markers: perhaps be able to differentiate the importance of an item from another using symbols 
such as \{!, *, ?\}.
- [ ] Perhaps make the default sizes of the task, event, and note containers a little smaller since they are quite large.
- [x] Make the words **Rapid Log** and the date line up with the edge of the tasks container.
- [x] Vertically center the **Migrate All Entries** button within its given space.

Comments:
- Really good job!

**Comment by joshua-j-hong** [comment]
904c856472cbf0b969d73696381d837661aef3ca addresses update 4 and 5. Although the Migrate All Entries is right aligned in its space, it is correctly lined up with the right edge

**Comment by Max-Edelson** [comment]
Done with rapid log.
