### ISSUE TITLE
ENHANCEMENT: Initial Nav Bar Thoughts

### ISSUE THREAD

**Issue by Max-Edelson** [Max-Edelson/cse110-sp21-group16#73]
Potential Updates/Fixes
- [x] Delete default custom logs in list, or have a distinct **Example** custom log that will have to be basically a tutorial custom log.
- [ ] For monthly log, make it a scroll bar with the first three showing, but have the next 6 in the list.
- [x] Is the home button a button because when the cursor is over it, it doesn't have the clicking option.

Comments:
- Really good job and these are just suggestions based on my initial thoughts.

**Comment by joshua-j-hong** [comment]
Will address these sometime Sunday night

**Comment by Max-Edelson** [comment]
Sounds good.

**Comment by joshua-j-hong** [comment]
904c856472cbf0b969d73696381d837661aef3ca added the first and second update. As in the meeting, adding entries that are more than 3 months in the future will be delegated to the future log.

**Comment by Max-Edelson** [comment]
Nav bar works.
