### ISSUE TITLE
Technical Debt Increasing

### ISSUE THREAD

**Issue by Max-Edelson** [Max-Edelson/cse110-sp21-group16#74]
Please visit the [codeClimate](https://codeclimate.com/github/Max-Edelson/cse110-sp21-group16) for our repository. You'll see that we are rated an F for maintainability due to duplication of code. I believe most of the duplication can be found in the Rapid Log files. If possible, please try to reduce the duplication, if not, just respond so in this thread and its aight.

I will continuously monitor codeClimate as we push more code to ```main```, and as it grows as an issue, I'll begin drawing the attention of specific people to certain files.

**Comment by joshua-j-hong** [comment]
I agree it's concerning, but at the present moment most the duplication is in code that is slated to be soon replaced. In the next few days the tech debt should decrease

**Comment by Max-Edelson** [comment]
Sounds good, I will then check back in a couple days.

**Comment by joshua-j-hong** [comment]
Addressed duplication in navbar and it should be resolved. As for the rest of the duplication, I will hopefully address it sometime Wednesday/Thursday when working with others who are available

**Comment by Max-Edelson** [comment]
Not enough time to fix duplication. Rip code climate report.
