### ISSUE TITLE
ENHANCEMENT: Add migration/edit functionality and popup

### ISSUE THREAD

**Issue by carmenli14** [Max-Edelson/cse110-sp21-group16#86]
**Enhancement details**
Currently focusing on daily log page.
Enable editing of each entry when the 'more options' button is clicked:

- [x] Add popup for each item 
- [x] Get rid of duplicate code, turn them into helper functions
- [x] Fix array names
- [ ] Fill input values of form with pre-existing values if editing, empty if adding new item
- [ ] Changed data will update in local storage
- [ ] Entries correctly display on respective months/days when we change the date (MIGRATION)

Other notes: we won't have "cross-migration" between custom and monthly logs, only within monthly.

**Comment by Max-Edelson** [comment]
Not enough time for migration.
